enum EnvValues {
  ENCRYPTER_SALT,
  API_KEY_WEB,
  API_KEY_ANDROID,
  API_KEY_IOS,
  API_KEY_MACOS,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
  ORDER_SPREADSHEET_ID,
  SPREADSHEET_URL,
  SENDER_EMAIL,
  SENDER_EMAIL_PASSWORD,
}
