// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJAT0ni0eYlPRZgCup_x2DT_0OJ8pnZok',
    appId: '1:704669957190:web:699cf5c9a0da9712e15e47',
    messagingSenderId: '704669957190',
    projectId: 'hulscoffeehouse',
    authDomain: 'hulscoffeehouse.firebaseapp.com',
    storageBucket: 'hulscoffeehouse.appspot.com',
    measurementId: 'G-S0BHJD1L7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlzJapdsoGe8UwcmD13UvMTGyNZdBpm8',
    appId: '1:704669957190:android:75120d8ceb62afaee15e47',
    messagingSenderId: '704669957190',
    projectId: 'hulscoffeehouse',
    storageBucket: 'hulscoffeehouse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsWKlGUgz0K4eUhD7K6omFpXb5Dn_uyeA',
    appId: '1:704669957190:ios:46510335164786a9e15e47',
    messagingSenderId: '704669957190',
    projectId: 'hulscoffeehouse',
    storageBucket: 'hulscoffeehouse.appspot.com',
    iosBundleId: 'com.example.hulsCoffeeHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsWKlGUgz0K4eUhD7K6omFpXb5Dn_uyeA',
    appId: '1:704669957190:ios:c5a7f4f473fb7725e15e47',
    messagingSenderId: '704669957190',
    projectId: 'hulscoffeehouse',
    storageBucket: 'hulscoffeehouse.appspot.com',
    iosBundleId: 'com.example.hulsCoffeeHouse.RunnerTests',
  );
}
